<a href="https://colab.research.google.com/github/daniel-usp/MachineLearning/blob/main/04%20-%20DecisionTrees/DecisionTreeClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.datasets import load_iris
import pandas as pd

#Banco de Dados Geral
dados = pd.read_excel('https://github.com/daniel-usp/MachineLearning/raw/main/04%20-%20DecisionTrees/assinatura.xlsx')
dados





idade  fatura  temp_cli  linhas    renda  temp_rsd  internet  premiere  \
0        51     543        26       4   5320.0       7.3         1         0   
1        36     482        16       2   5620.0       4.5         1         0   
2        35     593        15       1   4860.0       4.8         0         0   
3        40    1184        22       1   6590.0       6.2         1         0   
4        52     634        30       1   6370.0       2.2         0         0   
...     ...     ...       ...     ...      ...       ...       ...       ...   
1994     31     625        15       4  10170.0       1.5         0         1   
1995     37    4322        18       4  12230.0       4.6         1         1   
1996     29     517        12       5   5590.0       6.7         1         0   
1997     34     528        14       1   4760.0       6.9         1         0   
1998     31    1076        20       1   6150.0       3.2         1         0   

      cancel  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
1994       1  
1995       1  
1996       1  
1997       1  
1998       1  

[1999 rows x 9 columns]

In [ ]:
#Declarar X e Y
y = dados['cancel']
x = dados.drop('cancel', axis =1)
features = x.columns


In [ ]:
#Separar em amostra treino e teste pelo sklearn

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier


# Dividir os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Cria um objeto do classificador DecisionTree
model = DecisionTreeClassifier(random_state=42)

# Treina o classificador com o conjunto de treinamento
model.fit(X_train, y_train)

# Calcula os cross validation scores
scores = cross_val_score(model, x, y, cv=5)

# Printa os scores
print('Cross-validation scores: ', scores)

# Printa a média dos scores
print('Average cross-validation score: ', scores.mean())



Cross-validation scores:  [0.71  0.74  0.725 0.715 0.69 ]
Average cross-validation score:  0.716


In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

#Criação do modelo
modelo = DecisionTreeClassifier()
resultado = cross_val_score(modelo, x,y, cv = 5)

#Imprimindo a acurácia
print(resultado.mean())



0.7250000000000001


In [ ]:
y.unique()

array([0, 1])

In [ ]:
import graphviz
from sklearn.tree import export_graphviz

In [ ]:
import io
import graphviz
from sklearn.tree import export_graphviz

# Ajustando o modelo
modelo.fit(x, y)

# Gerando o gráfico da árvore de decisão:
features = x.columns
class_names = ['y=0', 'y=1']  # Rótulos das classes alvo

dot_data = io.StringIO()
export_graphviz(modelo, out_file=dot_data, feature_names=features, class_names=class_names, filled=True, proportion=True)

graph = graphviz.Source(dot_data.getvalue())
graph.view()


'Source.gv.pdf'

In [ ]:
valores = y.unique()
valores

array([0, 1])

In [ ]:
import numpy as np
from sklearn.model_selection import GridSearchCV

#Definindo os valores que serão testados em DecisionTree:
minimos_split = np.array([2,3,4,5,6,7,8])
maximo_nivel = np.array([3,4,5,6,7,8,9])
algoritmo = ['gini']
valores_grid = {'min_samples_split': minimos_split, 'max_depth': maximo_nivel, 'criterion': algoritmo}

#Criação do Modelo
modelo = DecisionTreeClassifier()

#Criando os grids
gridDecisionTree = GridSearchCV(estimator = modelo, param_grid = valores_grid, cv = 5)
gridDecisionTree.fit(x,y)

#Imprimindo os melhores parâmetros
print("Mínimo split: ", gridDecisionTree.best_estimator_.min_samples_split)
print("Máxima profundidade: ", gridDecisionTree.best_estimator_.max_depth)
print("Critério: ", gridDecisionTree.best_estimator_.criterion)
print("Acurácia: ", gridDecisionTree.best_score_)


Mínimo split:  2
Máxima profundidade:  3
Critério:  gini
Acurácia:  0.783


In [ ]:
import io
import graphviz
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz

# Ajuste do melhor modelo
melhor_modelo = DecisionTreeClassifier(min_samples_split = gridDecisionTree.best_estimator_.min_samples_split,
                                      max_depth = gridDecisionTree.best_estimator_.max_depth)
melhor_modelo.fit(x, y)

# Gerando o gráfico da árvore de decisão:
features = x.columns
class_names = ['Not Cancel', 'Cancel']  # Rótulos das classes alvo

dot_data = io.StringIO()
export_graphviz(melhor_modelo, out_file=dot_data, feature_names=features, class_names=class_names, filled=True, proportion=True)

graph = graphviz.Source(dot_data.getvalue())
graph.view()


'Source.gv.pdf'

In [ ]:
dados = [[50,20,100,5000,20,1,0,500],[60,10,200,4000,20,1,0,50]]

melhor_modelo.predict(dados)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0, 0])